# Generated by Django 6.0 on 2026-01-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_registered",
            field=models.BooleanField(default=True),
        ),
    ]
