# Generated by Django 6.0 on 2026-01-10 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_is_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
